name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      
      - name: Create virtual environment
        run: uv venv

      - name: Cache uv dependencies
        id: cache-uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: cache-3ee2436

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Prime cache
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "âœ… Cache hit! Dependencies were restored."
          else
            echo "ðŸ†• Cache miss. Dependencies were installed and cache will be saved."
          fi
